server:
  port: 7070


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lanzeloth03/CICLO-5-G-1 .git # ruta del repositorio git
          searchPaths: config-data
          default-label: main
          #username:
          #password:

  security:
    user:
      name: root
      password: 123456